stages:
  - lint
  - build

fmt:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
  tags:
    - asprunner

clippy:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings
  tags:
    - asprunner

check-for-todos:
  stage: lint
  image: rust:latest
  script:
    - make check-for-todos
  artifacts:
    when: always
    reports:
    paths:
      - ./check_for_todos_results.txt
    expire_in: 2 week
  allow_failure: true
  tags:
    - asprunner

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
  tags:
    - asprunner

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
  tags:
    - asprunner
