[package]
name = "lms"
version = "0.1.0"
authors = ["Maurice Hieronymus <maurice_hieronymus@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.1"
rand = "0.8.3"
sha2 = "0.9.3"

[dev-dependencies]
clap = "2.33.3"
tempfile = "3.2.0"